module.exports = [
  {
    name: 'edutechlife-backend-src',
    files: ['src/**/*.js'],
    ignores: ['src/__tests__/**', 'src/**/*.test.js', 'src/**/*.spec.js'],
    languageOptions: {
      ecmaVersion: 2025,
      sourceType: 'module',
      globals: {
        process: 'readonly',
        Buffer: 'readonly',
        __dirname: 'readonly',
        __filename: 'readonly',
        global: 'readonly',
        console: 'readonly',
        setTimeout: 'readonly',
        clearTimeout: 'readonly',
        setInterval: 'readonly',
        clearInterval: 'readonly',
        require: 'readonly',
        module: 'readonly',
        exports: 'readonly',
        TextDecoder: 'readonly',
        TextEncoder: 'readonly',
      },
    },
    rules: {
      'no-console': 'off',
      'no-unused-vars': ['warn', { argsIgnorePattern: '^_', varsIgnorePattern: '^_' }],
      'no-debugger': 'error',
      'no-duplicate-imports': 'error',
      'max-lines': ['warn', { max: 400, skipBlankLines: true, skipComments: true }],
      'no-undef': 'error',
      'no-empty': 'warn',
    },
  },
  {
    name: 'edutechlife-backend-tests',
    files: ['src/__tests__/**', 'src/**/*.test.js', 'src/**/*.spec.js', 'src/test-setup.js'],
    languageOptions: {
      ecmaVersion: 2025,
      sourceType: 'module',
      globals: {
        process: 'readonly',
        Buffer: 'readonly',
        __dirname: 'readonly',
        __filename: 'readonly',
        global: 'readonly',
        console: 'readonly',
        require: 'readonly',
        module: 'readonly',
        exports: 'readonly',
        TextDecoder: 'readonly',
        TextEncoder: 'readonly',
        describe: 'readonly',
        it: 'readonly',
        expect: 'readonly',
        beforeEach: 'readonly',
        afterEach: 'readonly',
        beforeAll: 'readonly',
        afterAll: 'readonly',
        vi: 'readonly',
        jest: 'readonly',
      },
    },
    rules: {
      'no-console': 'off',
      'no-unused-vars': ['warn', { argsIgnorePattern: '^_', varsIgnorePattern: '^_' }],
      'no-debugger': 'error',
      'no-empty': 'warn',
      'max-lines': 'off',
    },
  },
  {
    ignores: ['node_modules', 'dist', 'coverage'],
  },
]
