export const MODULE_PRINCIPLES = {
  1: { role: { es: "El Artesano Digital", en: "The Digital Artisan", pt: "O Artesão Digital" }, principle: "Precisión", principleLine: "Una instrucción precisa transforma el resultado" },
  2: { role: { es: "El Arquitecto de Automatización", en: "The Automation Architect", pt: "O Arquiteto de Automação" }, principle: "Estructura", principleLine: "Lo que se diseña bien se automatiza mejor" },
  3: { role: { es: "El Detective de Datos", en: "The Data Detective", pt: "O Detetive de Dados" }, principle: "Evidencia", principleLine: "Solo lo verificado es conocimiento" },
  4: { role: { es: "El Alquimista del Conocimiento", en: "The Knowledge Alchemist", pt: "O Alquimista do Conhecimento" }, principle: "Síntesis", principleLine: "Todo documento puede transmutarse en conocimiento" },
  5: { role: { es: "El Guardián de la IA", en: "The AI Guardian", pt: "O Guardião da IA" }, principle: "Responsabilidad", principleLine: "El poder sin ética es riesgo" },
};

export const METHODOLOGY_PRINCIPLES = [
  { id: "vak", name: { es: "Brújula VAK", en: "VAK Compass", pt: "Bússola VAK" }, principle: "Personalización" },
  { id: "steam", name: { es: "Enfoque STEAM", en: "STEAM Approach", pt: "Abordagem STEAM" }, principle: "Integración" },
  { id: "abr", name: { es: "Método Reto", en: "Challenge Method", pt: "Método Desafio" }, principle: "Aplicación" },
  { id: "neuro", name: { es: "Diseño Neurocognitivo", en: "Neurocognitive Design", pt: "Design Neurocognitivo" }, principle: "Retención" },
  { id: "max", name: { es: "Acompañamiento MAX", en: "MAX Companionship", pt: "Acompanhamento MAX" }, principle: "Acompañamiento" },
  { id: "gamification", name: { es: "Motor de Progreso", en: "Progress Engine", pt: "Motor de Progresso" }, principle: "Motivación" },
  { id: "edutechlife", name: { es: "Ruta Edutechlife", en: "Edutechlife Path", pt: "Rota Edutechlife" }, principle: "Progresión" },
];

export const OVA_REGISTRY = [
  { code: "ILAB-M1-OVA1", module: 1, status: "active", resourceId: "intro-ova-1", component: "OVAEtica",
    name: { es: "La Materia Prima", en: "The Raw Material", pt: "A Matéria-Prima" },
    descriptor: { es: "Orígenes de la IA y el prompt", en: "Origins of AI and the prompt", pt: "Origens da IA e do prompt" },
    principle: "Contexto" },
  { code: "ILAB-M1-OVA2", module: 1, status: "active", resourceId: "prompt-ova-html-1", component: "OVAIntroPrompt",
    name: { es: "El Cincel", en: "The Chisel", pt: "O Cinzel" },
    descriptor: { es: "Fundamentos del prompt y su anatomía", en: "Prompt fundamentals and anatomy", pt: "Fundamentos e anatomia do prompt" },
    principle: "Claridad" },
  { code: "ILAB-M1-OVA3", module: 1, status: "active", resourceId: "prompt-lab-ova-1", component: "OVAPromptLab",
    name: { es: "El Martillo", en: "The Hammer", pt: "O Martelo" },
    descriptor: { es: "Laboratorio de prompts en vivo", en: "Live prompt laboratory", pt: "Laboratório de prompts ao vivo" },
    principle: "Práctica deliberada" },
  { code: "ILAB-M2-OVA1", module: 2, status: "active", resourceId: "chatgpt-ova-ecosystem", component: "OVAEcosystemGuide",
    name: { es: "El Plano Maestro", en: "The Master Blueprint", pt: "A Planta Mestra" },
    descriptor: { es: "Mapa del ecosistema ChatGPT", en: "Map of the ChatGPT ecosystem", pt: "Mapa do ecossistema ChatGPT" },
    principle: "Visión sistémica" },
  { code: "ILAB-M2-OVA2", module: 2, status: "active", resourceId: "workflow-ova-herramientas", component: "OVAChatGPTTools",
    name: { es: "La Caja de Herramientas", en: "The Toolbox", pt: "A Caixa de Ferramentas" },
    descriptor: { es: "Arsenal integrado de ChatGPT", en: "ChatGPT integrated toolkit", pt: "Arsenal integrado do ChatGPT" },
    principle: "Herramienta correcta" },
  { code: "ILAB-M2-OVA3", module: 2, status: "active", resourceId: "automation-flows-ova-1", component: "OVAAutomationFlows",
    name: { es: "La Línea de Montaje", en: "The Assembly Line", pt: "A Linha de Montagem" },
    descriptor: { es: "Flujos de automatización", en: "Automation flows", pt: "Fluxos de automação" },
    principle: "Eficiencia" },
  { code: "ILAB-M2-OVA4", module: 2, status: "active", resourceId: "gpts-ova-1", component: "OVABuildGPT",
    name: { es: "La Fábrica de Asistentes", en: "The Assistant Factory", pt: "A Fábrica de Assistentes" },
    descriptor: { es: "Construye tu GPT", en: "Build your GPT", pt: "Construa seu GPT" },
    principle: "Personalización" },
  { code: "ILAB-M3-OVA1", module: 3, status: "active", resourceId: "workspace-ova-1", component: "OvaEdutechlife",
    name: { es: "La Lupa Multimodal", en: "The Multimodal Lens", pt: "A Lupa Multimodal" },
    descriptor: { es: "Misión Gemini", en: "Gemini mission", pt: "Missão Gemini" },
    principle: "Observación" },
  { code: "ILAB-M3-OVA2", module: 3, status: "active", resourceId: "gemini-cases-ova-1", component: "OVAPracticalCases",
    name: { es: "El Caso Abierto", en: "The Open Case", pt: "O Caso Aberto" },
    descriptor: { es: "Casos prácticos con Gemini", en: "Practical cases with Gemini", pt: "Casos práticos com Gemini" },
    principle: "Aplicación" },
  { code: "ILAB-M3-OVA3", module: 3, status: "active", resourceId: "gemini-deep-research-ova-1", component: "OVAGeminiDeepResearch",
    name: { es: "El Archivo Forense", en: "The Forensic Archive", pt: "O Arquivo Forense" },
    descriptor: { es: "Investigación profunda y verificación", en: "Deep research and verification", pt: "Pesquisa profunda e verificação" },
    principle: "Verificación" },
  { code: "ILAB-M4-OVA1", module: 4, status: "active", resourceId: "notebooklm-ova-1", component: "OVANotebookLab",
    name: { es: "El Grimorio", en: "The Grimoire", pt: "O Grimório" },
    descriptor: { es: "Construye tu notebook inteligente", en: "Build your smart notebook", pt: "Construa seu notebook inteligente" },
    principle: "Curaduría" },
  { code: "ILAB-M4-OVA2", module: 4, status: "active", resourceId: "notebook-summary-ova-1", component: "OVANotebookSimulator",
    name: { es: "El Crisol", en: "The Crucible", pt: "O Crisol" },
    descriptor: { es: "Simulador de análisis documental", en: "Document analysis simulator", pt: "Simulador de análise documental" },
    principle: "Síntesis" },
  { code: "ILAB-M4-OVA3", module: 4, status: "active", resourceId: "notebook-audio-guide-1", component: "OVANotebookPodcastGuide",
    name: { es: "La Fórmula Sonora", en: "The Sound Formula", pt: "A Fórmula Sonora" },
    descriptor: { es: "Guía de Audio Overviews", en: "Audio Overviews guide", pt: "Guia de Audio Overviews" },
    principle: "Divulgación" },
  { code: "ILAB-M4-OVA4", module: 4, status: "active", resourceId: "notebook-audio-ova-1", component: "OVAPodcastStudio",
    name: { es: "El Estudio Alquímico", en: "The Alchemical Studio", pt: "O Estúdio Alquímico" },
    descriptor: { es: "Crea tu podcast IA", en: "Create your AI podcast", pt: "Crie seu podcast de IA" },
    principle: "Creación" },
  { code: "ILAB-M4-OVA5", module: 4, status: "active", resourceId: "document-mastery-ova-1", component: "OVADocumentMastery",
    name: { es: "La Transmutación", en: "The Transmutation", pt: "A Transmutação" },
    descriptor: { es: "Del documento al podcast", en: "From document to podcast", pt: "Do documento ao podcast" },
    principle: "Transformación" },
  { code: "ILAB-M5-OVA1", module: 5, status: "active", resourceId: "bias-ova-1", component: "OVABiasLab",
    name: { es: "El Espejo de la Verdad", en: "The Mirror of Truth", pt: "O Espelho da Verdade" },
    descriptor: { es: "Detector de sesgos", en: "Bias detector", pt: "Detector de vieses" },
    principle: "Equidad" },
  { code: "ILAB-M5-OVA2", module: 5, status: "active", resourceId: "privacy-ova-1", component: "OVARiskSimulator",
    name: { es: "La Brújula de Riesgos", en: "The Risk Compass", pt: "A Bússola de Riscos" },
    descriptor: { es: "Privacidad y evaluación de riesgos", en: "Privacy and risk assessment", pt: "Privacidade e avaliação de riscos" },
    principle: "Prudencia" },
  { code: "ILAB-M5-OVA3", module: 5, status: "active", resourceId: "ethics-ova-1", component: "OVAEthicalDilemmas",
    name: { es: "El Tribunal Ético", en: "The Ethical Tribunal", pt: "O Tribunal Ético" },
    descriptor: { es: "Dilemas éticos", en: "Ethical dilemmas", pt: "Dilemas éticos" },
    principle: "Juicio" },
  { code: "ILAB-M5-OVA4", module: 5, status: "active", resourceId: "ethics-cases-ova-1", component: "OVAEthicsCases",
    name: { es: "Casos del Guardián", en: "The Guardian's Cases", pt: "Os Casos do Guardião" },
    descriptor: { es: "Ética aplicada al mundo real", en: "Applied ethics in the real world", pt: "Ética aplicada ao mundo real" },
    principle: "Consecuencia" },
];

export function getOvaByCode(code) {
  return OVA_REGISTRY.find((o) => o.code === code) || null;
}
export function getOvaByResourceId(resourceId) {
  return OVA_REGISTRY.find((o) => o.resourceId === resourceId) || null;
}
export function getActiveOvas() {
  return OVA_REGISTRY.filter((o) => o.status === "active");
}
