/**
 * Configuración del carrusel del Hero.
 * `duration` en ms para slides temporizados; `null` = el video define la duración.
 */
export const HERO_SLIDES = [
  {
    id: "edutechlife",
    kind: "photo",
    duration: 9000,
    tabKey: "hero.tab_edutechlife",
    tabShort: "Edutechlife",
    tabImage: "/images/hero/icons/brain-teal.png",
    tabImageClass: "scale-[0.8] bg-[#e6f7f8]",
    tabCaptionKey: "hero.tab_edutechlife_caption",
    accent: "#0097A7",
    glow: "radial-gradient(55% 60% at 72% 45%, rgba(102,204,204,0.38), transparent 70%)",
    aurora: ["rgba(102,204,204,0.45)", "rgba(77,168,196,0.35)"],
  },
  {
    id: "ialab",
    kind: "video",
    duration: null,
    tabKey: "hero.tab_ialab",
    tabShort: "AI Lab",
    tabImage: "/images/hero/max.webp",
    tabImageClass: "scale-[1.15]",
    tabCaptionKey: "hero.tab_ialab_caption",
    accent: "#0097A7",
    glow: "radial-gradient(55% 60% at 72% 45%, rgba(0,151,167,0.34), transparent 70%)",
    aurora: ["rgba(0,151,167,0.4)", "rgba(0,75,99,0.25)"],
    route: "/ialab-academic",
    url: "edutechlife.co/ialab-academic",
    video: "/videos/hero/ialab-max.mp4",
    poster: "/images/hero/ialab-max-poster.webp",
    avatar: "/images/hero/max.webp",
    screenBg: "#06222E",
    titleKey: "hero.ialab_title",
    subtitleKey: "hero.ialab_subtitle",
    factKeys: ["hero.ialab_fact_1", "hero.ialab_fact_2"],
    ctaKey: "hero.ialab_cta",
    ctaClass: "bg-petroleum hover:bg-petroleum-dark",
    chipKey: "hero.ialab_chip",
    speaker: "MAX",
    liveCard: {
      type: "route",
      titleKey: "hero.ialab_live_title",
      fromKey: "hero.ialab_live_from",
      toKey: "hero.ialab_live_to",
    },
    listenKey: "hero.ialab_listen",
    muteKey: "hero.ialab_mute",
    videoLabelKey: "hero.ialab_video_label",
  },
  {
    id: "ingenia",
    kind: "video",
    duration: null,
    tabKey: "hero.tab_ingenia",
    tabShort: "IngenIA",
    tabImage: "/images/hero/dani.webp",
    tabImageClass: "scale-[1.25] translate-y-[8%] bg-[#eef0ff]",
    tabCaptionKey: "hero.tab_ingenia_caption",
    accent: "#7B2FF7",
    glow: "radial-gradient(55% 60% at 72% 45%, rgba(123,47,247,0.22), transparent 70%), radial-gradient(40% 45% at 60% 70%, rgba(0,194,224,0.22), transparent 70%)",
    aurora: ["rgba(123,47,247,0.3)", "rgba(0,194,224,0.35)"],
    route: "/conoce-ingenia",
    url: "edutechlife.co/ingenia",
    video: "/videos/hero/ingenia-dani.mp4",
    poster: "/images/hero/ingenia-dani-poster.webp",
    avatar: "/images/hero/dani.webp",
    screenBg: "#0B1D3A",
    titleKey: "hero.ingenia_title",
    subtitleKey: "hero.ingenia_subtitle",
    factKeys: ["hero.ingenia_fact_1", "hero.ingenia_fact_2"],
    ctaKey: "hero.ingenia_cta",
    ctaClass: "bg-[#0B1D3A] hover:bg-[#4361EE]",
    chipKey: "hero.ingenia_chip",
    speaker: "Dani",
    liveCard: {
      type: "plan",
      titleKey: "hero.ingenia_live_title",
      items: [
        { key: "hero.ingenia_live_math", value: 0.78 },
        { key: "hero.ingenia_live_lang", value: 0.6 },
        { key: "hero.ingenia_live_sci", value: 0.9 },
      ],
    },
    listenKey: "hero.ingenia_listen",
    muteKey: "hero.ingenia_mute",
    videoLabelKey: "hero.ingenia_video_label",
  },
];
