import json, os

SRC_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', 'src', 'i18n')
ES_PATH = os.path.join(SRC_DIR, 'es.json')
KEYS_PATH = os.path.join(SRC_DIR, 'keys.d.ts')

es = json.load(open(ES_PATH, 'r'))
keys = sorted(es.keys())

lines = ['// Auto-generated by sync-i18n-types script',
         'export type TranslationKeys = {']
for k in keys:
    lines.append(f'  "{k}": string;')
lines.append('};')
lines.append('')
lines.append('export type TranslationKey = keyof TranslationKeys;')
lines.append('')
lines.append('export const isTranslationKey = (key: string): key is TranslationKey => {')
lines.append('  return key in translationKeySet;')
lines.append('};')
lines.append('')
lines.append('const translationKeySet: Record<string, true> = {')
for k in keys:
    lines.append(f'  "{k}": true,')
lines.append('};')

content = '\n'.join(lines) + '\n'
open(KEYS_PATH, 'w').write(content)
print(f'Generated {len(keys)} keys in keys.d.ts')
