export const createSeguridadSlice = (set, get) => ({
  showExitConfirmation: false,
  setShowExitConfirmation: (v) => set({ showExitConfirmation: v }),
  showSecurityWarning: false,
  setShowSecurityWarning: (v) => set({ showSecurityWarning: v }),
  securityWarningCount: 0,
  setSecurityWarningCount: (v) => set({ securityWarningCount: v }),
  screenshotProtectionActive: false,
  setScreenshotProtectionActive: (v) => set({ screenshotProtectionActive: v }),
  securityViolations: 0,
  setSecurityViolations: (v) => set({ securityViolations: v }),
  attemptsPenalized: 0,
  setAttemptsPenalized: (v) => set({ attemptsPenalized: v }),
  keyboardLockActive: false,
  setKeyboardLockActive: (v) => set({ keyboardLockActive: v }),
  showSecurityStatus: false,
  setShowSecurityStatus: (v) => set({ showSecurityStatus: v }),
  securityMessage: '',
  setSecurityMessage: (v) => set({ securityMessage: v }),
  showSecurityMessage: false,
  setShowSecurityMessage: (v) => set({ showSecurityMessage: v }),
});
