// Icon mapping utility for migrating from Font Awesome to Lucide React
// Maps Font Awesome class names to Lucide React components

import {
  Brain,
  Bot,
  LayoutTemplate,
  TrendingUp,
  Rocket,
  ArrowRight,
  ArrowLeft,
  Flag,
  X,
  Sun,
  Moon,
  WandSparkles,
  Users,
  Building,
  PieChart,
  Headphones,
  Headset,
  Building2,
  Zap,
  Target,
  Clock,
  Award,
  Trophy,
  GraduationCap,
  Play,
  BookOpen,
  Mic,
  MessageCircle,
  LogOut,
  Download,
  FileText,
  Eye,
  CheckCircle,
  CheckCheck,
  PlayCircle,
  Lock,
  Atom,
  Globe,
  Code,
  Music,
  Palette,
  Sparkles,
  Volume2,
  MicOff,
  VolumeX,
  Send,
  Settings,
  Subtitles,
  User,
  Keyboard,
  RefreshCw,
  History,
  Trash2,
  Shield,
  EyeOff,
  AlertCircle,
  Search,
  Filter,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  TrendingDown,
  BarChart3,
  Home,
  Cpu,
  Star,
  Flame,
  Calculator,
  FolderOpen,
  CircleHelp,
  LifeBuoy,
  Hand,
  // Additional icons for coverage
  Maximize,
  Minimize,
  Monitor,
  Bell,
  Key,
  UserCircle,
  IdCard,
  Globe2,
  File,
  MessageSquare,
  TriangleAlert,
  // Icon aliases
  CalculatorIcon,
  TargetIcon,
  ClockIcon,
  AwardIcon,
  TrophyIcon,
  GraduationCapIcon,
  PlayIcon,
  BookOpenIcon,
  MicIcon,
  MessageCircleIcon,
  LogOutIcon,
  DownloadIcon,
  FileTextIcon,
  EyeIcon,
  CheckCircleIcon,
  PlayCircleIcon,
  LockIcon,
  AtomIcon,
  GlobeIcon,
  CodeIcon,
  MusicIcon,
  PaletteIcon,
  SparklesIcon,
  Volume2Icon,
  MicOffIcon,
  VolumeXIcon,
  SendIcon,
  SettingsIcon,
  SubtitlesIcon,
  KeyboardIcon,
  RefreshCwIcon,
  HistoryIcon,
  Trash2Icon,
  ShieldIcon,
  UserIcon,
  EyeOffIcon,
  AlertCircleIcon,
  SearchIcon,
  FilterIcon,
  ChevronDownIcon,
  TrendingDownIcon,
  BarChart3Icon,
  HomeIcon,
  CpuIcon,
  ChevronRightIcon,
  StarIcon,
  FlameIcon,
  Lightbulb,
  Heart,
  Bookmark,
  UsersRound,
  CalculatorIcon as CalcIcon,
  Box,
  Terminal,
  ClipboardCheck,
  Tag,
  Mail,
  Check,
  Handshake,
  FlaskConical,
  Video,
  Phone,
  MapPin,
  ShieldCheck,
  Sliders,
  Coins,
    Calendar,
    PiggyBank,
    Network,
    Copy,
    Paperclip,
    Signal,
    Briefcase,
    RotateCw,
    Route,
    Laptop,
    School,
    Quote,
    Facebook,
    Instagram,
    Linkedin,
    Youtube,
    Puzzle,
    FileImage,
    Image,
    Layers,
    Clipboard,
    Info,
    Menu,
    Book,
    MousePointerClick,
    List,
     Gauge,
     Pencil,
     Camera,
     UserPlus,
      Smile,
      Podcast,
      Scale,
      LoaderCircle,
      Plus,
      Share2,
      Reply,
      Undo2,
      Save,
      ExternalLink,
      XCircle,
      Folder,
      Gamepad2,
      Hourglass,
      ListChecks,
      BellOff,
      ArrowDown,
      ArrowUp,
      ArrowUpRightFromSquare,
      ScrollText,
      Weight,
      Ear,
      Shapes,
      CircleDot,
      FileQuestion,
      VideoOff,
      CirclePlus,
      Images,
      CreditCard,
       CloudUpload,
       Compass
} from 'lucide-react';

// Mapping of Font Awesome class names to Lucide components
export const faToLucideMap = {
  // Brain/Intelligence icons
  'fa-brain': Brain,
  'fa-robot': Bot,
  'fa-chalkboard': LayoutTemplate,
  'fa-chart-line': TrendingUp,
  'fa-rocket': Rocket,
  'fa-flag': Flag,
  'fa-arrow-right': ArrowRight,
  'fa-xmark': X,
  'fa-sun': Sun,
  'fa-moon': Moon,
  'fa-wand-magic-sparkles': WandSparkles,
  'fa-certificate': Award,
  'fa-users': Users,
  'fa-handshake': Handshake,
  'fa-flask-vial': FlaskConical,
  'fa-flask': FlaskConical,
  'fa-building': Building2,
  'fa-chart-pie': PieChart,
  'fa-headset': Headphones,
  'fa-headphones': Headphones,
  'fa-line-chart': TrendingUp,
  'fa-pie-chart': PieChart,
  'fa-building-alt': Building2,
  'fa-rocket-launch': Rocket,
  'fa-bolt': Zap,
  'fa-target': Target,
  'fa-clock': Clock,
  'fa-award': Award,
  'fa-trophy': Trophy,
  'fa-graduation-cap': GraduationCap,
  'fa-play': Play,
  'fa-book-open': BookOpen,
  'fa-microphone': Mic,
  'fa-message': MessageCircle,
  'fa-sign-out-alt': LogOut,
  'fa-download': Download,
  'fa-file-text': FileText,
  'fa-eye': Eye,
  'fa-check-circle': CheckCircle,
  'fa-check-double': CheckCheck,
  'fa-play-circle': PlayCircle,
  'fa-lock': Lock,
  'fa-atom': Atom,
  'fa-globe': Globe,
  'fa-code': Code,
  'fa-music': Music,
  'fa-palette': Palette,
  'fa-sparkles': Sparkles,
  'fa-volume-up': Volume2,
  'fa-microphone-slash': MicOff,
  'fa-volume-mute': VolumeX,
  'fa-paper-plane': Send,
  'fa-cog': Settings,
  'fa-closed-captioning': Subtitles,
  'fa-keyboard': Keyboard,
  'fa-sync': RefreshCw,
  'fa-history': History,
  'fa-trash': Trash2,
  'fa-trash-can': Trash2,
   'fa-shield-alt': Shield,
  'fa-shield-halved': Shield,
  'fa-user': User,
  'fa-eye-slash': EyeOff,
  'fa-exclamation-circle': AlertCircle,
  'fa-circle-exclamation': AlertCircle,
  'fa-search': Search,
  'fa-filter': Filter,
  'fa-chevron-down': ChevronDown,
  'fa-chevron-right': ChevronRight,
  'fa-chevron-left': ChevronLeft,
  'fa-chart-line-down': TrendingDown,
  'fa-chart-bar': BarChart3,
  'fa-home': Home,
  'fa-house': Home,
  'fa-microchip': Cpu,
  'fa-star': Star,
  'fa-fire': Flame,
  'fa-calculator': Calculator,
  'fa-lightbulb': Lightbulb,
  'fa-heart': Heart,
  'fa-microchip-alt': Cpu,
  'fa-bookmark': Bookmark,
  'fa-users-cog': UsersRound,
  'fa-terminal': Terminal,
  'fa-clipboard-check': ClipboardCheck,
  'fa-medal': Award,

  'fa-chevron-up': ChevronUp,
  'fa-cubes': Box,
  'fa-tag': Tag,
  'fa-envelope': Mail,
  'fa-check': Check,
  'fa-arrow-left': ArrowLeft,
   'fa-arrow-trend-up': TrendingUp,
  'fa-chalkboard-teacher': GraduationCap,
  'fa-video': Video,
  'fa-phone': Phone,
  'fa-location-dot': MapPin,
  'fa-shield-check': ShieldCheck,
  'fa-sliders': Sliders,
  'fa-coins': Coins,
   'fa-calendar': Calendar,
   'fa-piggy-bank': PiggyBank,
    'fa-sitemap': Network,
    'fa-copy': Copy,
    'fa-paperclip': Paperclip,
    'fa-signal': Signal,
    'fa-briefcase': Briefcase,
    'fa-rotate-right': RotateCw,
    'fa-route': Route,
    'fa-laptop-code': Laptop,
    'fa-school': School,
    'fa-quote-right': Quote,
  'fa-user-graduate': GraduationCap,
  'fa-user-tie': User,
  'fa-bullseye': Target,
  'fa-facebook-f': Facebook,
  'fa-instagram': Instagram,
  'fa-linkedin-in': Linkedin,
  'fa-youtube': Youtube,
  'fa-folder-open': FolderOpen,
  'fa-circle-question': CircleHelp,
  'fa-life-ring': LifeBuoy,
  'fa-hand': Hand,
  'fa-whatsapp': MessageCircle,
  // New mappings for missing icons
  'fa-user-circle': UserCircle,
  'fa-times': X,
  'fa-sliders-h': Sliders,
  'fa-question-circle': CircleHelp,
  'fa-user-shield': Shield,
  'fa-desktop': Monitor,
  'fa-bell': Bell,
  'fa-key': Key,
  'fa-id-card': IdCard,
  'fa-trash-alt': Trash2,
  'fa-language': Globe2,
  'fa-file-alt': File,
  'fa-file': File,
  'fa-file-pdf': FileImage,
  'fa-file-lines': FileText,
  'fa-expand': Maximize,
  'fa-compress': Minimize,
    'fa-image': Image,
    'fa-images': Images,
    'fa-puzzle-piece': Puzzle,
  'fa-comments': MessageSquare,
  'fa-comment-dots': MessageCircle,
  'fa-exclamation-triangle': TriangleAlert,
  // Phase 1: Critical missing mappings
  'fa-layer-group': Layers,
  'fa-bars': Menu,
  'fa-video-camera': Video,
  'fa-clipboard': Clipboard,
  'fa-info-circle': Info,
  'fa-pencil': Pencil,
  'fa-camera': Camera,
  // Phase 2: ActivityHistory missing icons
  'fa-book': Book,
  'fa-file-image': FileImage,
   'fa-hand-pointer': MousePointerClick,
   'fa-list': List,
   'fa-tachometer-alt': Gauge,
   'fa-user-plus': UserPlus,
   'fa-quote-left': Quote,
   'fa-face-smile': Smile,
   'fa-podcast': Podcast,
   'fa-balance-scale': Scale,
   'fa-google': Search,
   'fa-google-plus': Search,
   'fa-google-drive': File,
   'fa-spinner': LoaderCircle,
    'fa-chart-simple': BarChart3,
    // Phase 3: Bulk missing mappings
    'fa-comment': MessageCircle,
    'fa-folder': Folder,
    'fa-cube': Box,
    'fa-plus': Plus,
    'fa-share': Share2,
    'fa-reply': Reply,
    'fa-pen': Pencil,
    'fa-undo': Undo2,
    'fa-save': Save,
    'fa-external-link': ExternalLink,
    'fa-external-link-alt': ExternalLink,
    'fa-arrow-up-right-from-square': ArrowUpRightFromSquare,
    'fa-times-circle': XCircle,
    'fa-circle-xmark': XCircle,
    'fa-xmark-circle': XCircle,
    'fa-credit-card': CreditCard,
    'fa-gamepad': Gamepad2,
    'fa-hourglass': Hourglass,
    'fa-hourglass-half': Hourglass,
    'fa-list-check': ListChecks,
    'fa-bell-slash': BellOff,
    'fa-arrow-down': ArrowDown,
    'fa-sign-out': LogOut,
    'fa-magic': WandSparkles,
    'fa-map-signs': Route,
    'fa-tasks': ListChecks,
    'fa-scroll': ScrollText,
    'fa-arrow-up': ArrowUp,
    'fa-arrow-up-from-square': ArrowUpRightFromSquare,
    'fa-redo': RotateCw,
    'fa-undo-alt': Undo2,
    'fa-edit': Pencil,
    'fa-circle-check': CheckCircle,
    'fa-circle-info': Info,
    'fa-weight-hanging': Weight,
    'fa-ear-listen': Ear,
    'fa-cubes': Shapes,
    'fa-diagram-project': Shapes,
    'fa-mouse-pointer': MousePointerClick,
    'fa-video-slash': VideoOff,
    'fa-plus-circle': CirclePlus,
    'fa-chart-network': Network,
    'fa-file-circle-question': FileQuestion,
    'fa-arrows-rotate': RotateCw,
    'fa-cloud-upload-alt': CloudUpload,
    'fa-pdf': FileText,
     'fa-bullet': CircleDot,
     'fa-compass': Compass,
       };

// Helper function to get Lucide component from Font Awesome class name
export function getLucideIcon(faClassName) {
  if (!faClassName) return null;
  // Normalize: remove common prefixes (fa-solid, fa-brands, fas, far, fal) and strip whitespace
  let cleanName = faClassName
    .replace(/^(fa-solid|fa-brands|fas|far|fal)\s+/i, '')
    .replace(/^fa-/, '');
  const key = `fa-${cleanName}`;
  
  if (faToLucideMap[key]) {
    return faToLucideMap[key];
  }
  
  // Fallback with console warning
  if (process.env.NODE_ENV !== 'production') {
    console.warn(`[iconMapping] Icon not found: "${faClassName}" — add mapping for "${key}" in iconMapping.jsx`);
  }
  return null;
}

// Component wrapper for easy usage
export function Icon({ name, className = "w-5 h-5", ...props }) {
  const LucideIcon = getLucideIcon(name);
  if (!LucideIcon) return null;
  return <LucideIcon className={className} aria-hidden="true" {...props} />;
}

// Export all Lucide icons for convenience

// Fix deploy 2
