// Icon mapping utility for migrating from Font Awesome to Lucide React
// Maps Font Awesome class names to Lucide React components

import {
  Brain,
  Bot,
  LayoutTemplate,
  TrendingUp,
  Rocket,
  ArrowRight,
  ArrowLeft,
  X,
  Sun,
  Moon,
  WandSparkles,
  Users,
  Building,
  PieChart,
  Headphones,
  Headset,
  Building2,
  Zap,
  Target,
  Clock,
  Award,
  Trophy,
  GraduationCap,
  Play,
  BookOpen,
  Mic,
  MessageCircle,
  LogOut,
  Download,
  FileText,
  Eye,
  CheckCircle,
  PlayCircle,
  Lock,
  Atom,
  Globe,
  Code,
  Music,
  Palette,
  Sparkles,
  Volume2,
  MicOff,
  VolumeX,
  Send,
  Settings,
  Subtitles,
  Keyboard,
  RefreshCw,
  History,
  Trash2,
  Shield,
  User,
  EyeOff,
  AlertCircle,
  Search,
  Filter,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  TrendingDown,
  BarChart3,
  Home,
  Cpu,
  Star,
  Flame,
  Calculator,
  // Additional icons for coverage

  CalculatorIcon,
  TargetIcon,
  ClockIcon,
  AwardIcon,
  TrophyIcon,
  GraduationCapIcon,
  PlayIcon,
  BookOpenIcon,
  MicIcon,
  MessageCircleIcon,
  LogOutIcon,
  DownloadIcon,
  FileTextIcon,
  EyeIcon,
  CheckCircleIcon,
  PlayCircleIcon,
  LockIcon,
  AtomIcon,
  GlobeIcon,
  CodeIcon,
  MusicIcon,
  PaletteIcon,
  SparklesIcon,
  Volume2Icon,
  MicOffIcon,
  VolumeXIcon,
  SendIcon,
  SettingsIcon,
  SubtitlesIcon,
  KeyboardIcon,
  RefreshCwIcon,
  HistoryIcon,
  Trash2Icon,
  ShieldIcon,
  UserIcon,
  EyeOffIcon,
  AlertCircleIcon,
  SearchIcon,
  FilterIcon,
  ChevronDownIcon,
  TrendingDownIcon,
  BarChart3Icon,
  HomeIcon,
  CpuIcon,
  ChevronRightIcon,
  StarIcon,
  FlameIcon,
  Lightbulb,
  Heart,
  Bookmark,
  UsersRound,
  CalculatorIcon as CalcIcon,
  Box,
  Terminal,
  ClipboardCheck,
  Tag,
  Mail,
  Check,
  Handshake,
  FlaskConical,
  Video,
  Phone,
  MapPin,
  ShieldCheck,
  Sliders,
  Coins,
    Calendar,
    PiggyBank,
    Network,
    Copy,
    Paperclip,
    Signal,
    Briefcase,
    RotateCw,
    Route,
    Laptop,
    School,
    Quote,
    Facebook,
    Instagram,
    Linkedin,
    Youtube
} from 'lucide-react';

// Mapping of Font Awesome class names to Lucide components
export const faToLucideMap = {
  // Brain/Intelligence icons
  'fa-brain': Brain,
  'fa-robot': Bot,
  'fa-chalkboard': LayoutTemplate,
  'fa-chart-line': TrendingUp,
  'fa-rocket': Rocket,
  'fa-arrow-right': ArrowRight,
  'fa-xmark': X,
  'fa-sun': Sun,
  'fa-moon': Moon,
  'fa-wand-magic-sparkles': WandSparkles,
  'fa-certificate': Award,
  'fa-users': Users,
  'fa-handshake': Handshake,
  'fa-flask-vial': FlaskConical,
  'fa-flask': FlaskConical,
  'fa-building': Building2,
  'fa-chart-pie': PieChart,
  'fa-headset': Headphones,
  'fa-headphones': Headphones,
  'fa-line-chart': TrendingUp,
  'fa-pie-chart': PieChart,
  'fa-building-alt': Building2,
  'fa-rocket-launch': Rocket,
  'fa-bolt': Zap,
  'fa-target': Target,
  'fa-clock': Clock,
  'fa-award': Award,
  'fa-trophy': Trophy,
  'fa-graduation-cap': GraduationCap,
  'fa-play': Play,
  'fa-book-open': BookOpen,
  'fa-microphone': Mic,
  'fa-message': MessageCircle,
  'fa-sign-out-alt': LogOut,
  'fa-download': Download,
  'fa-file-text': FileText,
  'fa-eye': Eye,
  'fa-check-circle': CheckCircle,
  'fa-play-circle': PlayCircle,
  'fa-lock': Lock,
  'fa-atom': Atom,
  'fa-globe': Globe,
  'fa-code': Code,
  'fa-music': Music,
  'fa-palette': Palette,
  'fa-sparkles': Sparkles,
  'fa-volume-up': Volume2,
  'fa-microphone-slash': MicOff,
  'fa-volume-mute': VolumeX,
  'fa-paper-plane': Send,
  'fa-cog': Settings,
  'fa-closed-captioning': Subtitles,
  'fa-keyboard': Keyboard,
  'fa-sync': RefreshCw,
  'fa-history': History,
  'fa-trash': Trash2,
   'fa-shield-alt': Shield,
  'fa-shield-halved': Shield,
  'fa-user': User,
  'fa-eye-slash': EyeOff,
  'fa-exclamation-circle': AlertCircle,
  'fa-search': Search,
  'fa-filter': Filter,
  'fa-chevron-down': ChevronDown,
  'fa-chevron-right': ChevronRight,
  'fa-chevron-left': ChevronLeft,
  'fa-chart-line-down': TrendingDown,
  'fa-chart-bar': BarChart3,
  'fa-home': Home,
  'fa-microchip': Cpu,
  'fa-star': Star,
  'fa-fire': Flame,
  'fa-calculator': Calculator,
  'fa-lightbulb': Lightbulb,
  'fa-heart': Heart,
  'fa-microchip-alt': Cpu,
  'fa-bookmark': Bookmark,
  'fa-users-cog': UsersRound,
  'fa-terminal': Terminal,
  'fa-clipboard-check': ClipboardCheck,
  'fa-medal': Award,

  'fa-chevron-up': ChevronUp,
  'fa-cubes': Box,
  'fa-tag': Tag,
  'fa-envelope': Mail,
  'fa-check': Check,
  'fa-arrow-left': ArrowLeft,
   'fa-arrow-trend-up': TrendingUp,
  'fa-chalkboard-teacher': GraduationCap,
  'fa-video': Video,
  'fa-phone': Phone,
  'fa-location-dot': MapPin,
  'fa-shield-check': ShieldCheck,
  'fa-sliders': Sliders,
  'fa-coins': Coins,
   'fa-calendar': Calendar,
   'fa-piggy-bank': PiggyBank,
    'fa-sitemap': Network,
    'fa-copy': Copy,
    'fa-paperclip': Paperclip,
    'fa-signal': Signal,
    'fa-briefcase': Briefcase,
    'fa-rotate-right': RotateCw,
    'fa-route': Route,
    'fa-laptop-code': Laptop,
    'fa-school': School,
    'fa-quote-right': Quote,
    'fa-user-graduate': GraduationCap,
    'fa-bullseye': Target,
    'fa-facebook-f': Facebook,
    'fa-instagram': Instagram,
    'fa-linkedin-in': Linkedin,
    'fa-youtube': Youtube,
};

// Helper function to get Lucide component from Font Awesome class name
export function getLucideIcon(faClassName) {
  // Remove 'fa-solid ', 'fa-brands ' or 'fa-' prefix if present
  const cleanName = faClassName.replace('fa-solid ', '').replace('fa-brands ', '').replace('fa-', '');
  const key = `fa-${cleanName}`;
  
  if (faToLucideMap[key]) {
    return faToLucideMap[key];
  }
  
  // Fallback to null (silent)
  return null;
}

// Component wrapper for easy usage
export function Icon({ name, className = "w-5 h-5", ...props }) {
  const LucideIcon = getLucideIcon(name);
  if (!LucideIcon) return null;
  return <LucideIcon className={className} {...props} />;
}

// Export all Lucide icons for convenience

// Fix deploy 2
