export { forumService } from "./forum/index";
export {
  getPosts,
  getPostsOptimized,
  createPost,
  updatePost,
  deletePost,
  upvotePost,
  removeVote,
  checkUserVote,
  getComments,
  getCommentsBatch,
  getPostDetails,
  addComment,
  getForumStats,
  getUserStats,
  getPopularTags,
  subscribeToForumUpdates,
  clearProfileCache,
  TABLES,
  VALIDATION,
} from "./forum/index";
