-- Module Content CMS: Curso IALab
-- Almacena contenido educativo, recursos y preguntas de quiz
-- Con fallback a datos hardcodeados en el frontend

-- 1. Módulos del curso
CREATE TABLE IF NOT EXISTS module_content (
  id INTEGER PRIMARY KEY,
  title TEXT NOT NULL,
  objective TEXT NOT NULL,
  description TEXT NOT NULL,
  mission TEXT,
  challenge_question TEXT DEFAULT '',
  learning_points JSONB DEFAULT '[]'::jsonb,
  overview_data JSONB DEFAULT '{}'::jsonb,
  is_active BOOLEAN DEFAULT true,
  sort_order INTEGER DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_module_content_active ON module_content(is_active);

-- 2. Lecciones por módulo
CREATE TABLE IF NOT EXISTS module_lessons (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  module_id INTEGER NOT NULL REFERENCES module_content(id) ON DELETE CASCADE,
  lesson_index INTEGER NOT NULL,
  title TEXT NOT NULL,
  description TEXT NOT NULL,
  detailed_description TEXT DEFAULT '',
  duration TEXT DEFAULT '15 min',
  format TEXT DEFAULT 'Reading' CHECK (format IN ('Reading', 'Lab', 'Video')),
  icon TEXT DEFAULT 'fa-book-open',
  badge_color TEXT DEFAULT '#004B63',
  theme_color TEXT DEFAULT '#004B63',
  accordion_content JSONB DEFAULT '{}'::jsonb,
  is_active BOOLEAN DEFAULT true,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now(),
  UNIQUE(module_id, lesson_index)
);

CREATE INDEX IF NOT EXISTS idx_module_lessons_module ON module_lessons(module_id);

-- 3. Topics con recursos
CREATE TABLE IF NOT EXISTS module_topics (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  module_id INTEGER NOT NULL REFERENCES module_content(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  description TEXT DEFAULT '',
  learning_objectives JSONB DEFAULT '[]'::jsonb,
  estimated_time TEXT DEFAULT '30 min',
  difficulty TEXT DEFAULT 'Intermedio' CHECK (difficulty IN ('Principiante', 'Intermedio', 'Avanzado')),
  sort_order INTEGER DEFAULT 0,
  is_active BOOLEAN DEFAULT true,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_module_topics_module ON module_topics(module_id);

-- 4. Recursos por topic
CREATE TABLE IF NOT EXISTS module_resources (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  topic_id UUID NOT NULL REFERENCES module_topics(id) ON DELETE CASCADE,
  type TEXT NOT NULL CHECK (type IN ('video', 'pdf', 'ova_interactive', 'ova', 'document', 'image')),
  title TEXT NOT NULL,
  url TEXT NOT NULL,
  description TEXT DEFAULT '',
  duration TEXT,
  thumbnail TEXT,
  provider TEXT,
  pages INTEGER,
  format TEXT,
  size TEXT,
  estimated_time TEXT,
  difficulty TEXT,
  interactive_elements INTEGER,
  metadata JSONB DEFAULT '{}'::jsonb,
  sort_order INTEGER DEFAULT 0,
  is_active BOOLEAN DEFAULT true,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_module_resources_topic ON module_resources(topic_id);

-- 5. Quiz questions
CREATE TABLE IF NOT EXISTS quiz_questions (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  module_id INTEGER NOT NULL REFERENCES module_content(id) ON DELETE CASCADE,
  question TEXT NOT NULL,
  options JSONB NOT NULL DEFAULT '[]'::jsonb,
  correct_answer TEXT NOT NULL,
  topic TEXT NOT NULL,
  difficulty TEXT DEFAULT 'medio' CHECK (difficulty IN ('fácil', 'medio', 'difícil')),
  feedback TEXT DEFAULT '',
  sort_order INTEGER DEFAULT 0,
  is_active BOOLEAN DEFAULT true,
  created_at TIMESTAMPTZ DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_quiz_questions_module ON quiz_questions(module_id);

-- 6. Función para obtener contenido completo de un módulo
CREATE OR REPLACE FUNCTION get_module_full(module_id INTEGER)
RETURNS JSONB LANGUAGE plpgsql AS $$
DECLARE
  result JSONB;
BEGIN
  SELECT jsonb_build_object(
    'module', row_to_json(mc)::jsonb,
    'lessons', COALESCE(jsonb_agg(ml ORDER BY ml.lesson_index) FILTER (WHERE ml.id IS NOT NULL), '[]'::jsonb),
    'topics', COALESCE(jsonb_agg(
      jsonb_build_object(
        'topic', row_to_json(mt)::jsonb,
        'resources', COALESCE(
          (SELECT jsonb_agg(row_to_json(mr)::jsonb ORDER BY mr.sort_order)
           FROM module_resources mr WHERE mr.topic_id = mt.id AND mr.is_active),
          '[]'::jsonb
        )
      ) ORDER BY mt.sort_order
    ) FILTER (WHERE mt.id IS NOT NULL), '[]'::jsonb),
    'quiz', COALESCE(jsonb_agg(qq ORDER BY qq.sort_order) FILTER (WHERE qq.id IS NOT NULL), '[]'::jsonb)
  ) INTO result
  FROM module_content mc
  LEFT JOIN module_lessons ml ON ml.module_id = mc.id AND ml.is_active
  LEFT JOIN module_topics mt ON mt.module_id = mc.id AND mt.is_active
  LEFT JOIN quiz_questions qq ON qq.module_id = mc.id AND qq.is_active
  WHERE mc.id = module_id
  GROUP BY mc.id;
  RETURN result;
END;
$$;

-- 7. Row Level Security
ALTER TABLE module_content ENABLE ROW LEVEL SECURITY;
ALTER TABLE module_lessons ENABLE ROW LEVEL SECURITY;
ALTER TABLE module_topics ENABLE ROW LEVEL SECURITY;
ALTER TABLE module_resources ENABLE ROW LEVEL SECURITY;
ALTER TABLE quiz_questions ENABLE ROW LEVEL SECURITY;

-- Todos los usuarios autenticados pueden leer contenido
CREATE POLICY "Anyone can read module_content"
  ON module_content FOR SELECT USING (true);
CREATE POLICY "Anyone can read module_lessons"
  ON module_lessons FOR SELECT USING (true);
CREATE POLICY "Anyone can read module_topics"
  ON module_topics FOR SELECT USING (true);
CREATE POLICY "Anyone can read module_resources"
  ON module_resources FOR SELECT USING (true);
CREATE POLICY "Anyone can read quiz_questions"
  ON quiz_questions FOR SELECT USING (true);

-- Solo admin puede modificar contenido
CREATE POLICY "Admin can insert module_content"
  ON module_content FOR INSERT WITH CHECK (auth.role() = 'service_role');
CREATE POLICY "Admin can update module_content"
  ON module_content FOR UPDATE USING (auth.role() = 'service_role');
CREATE POLICY "Admin can delete module_content"
  ON module_content FOR DELETE USING (auth.role() = 'service_role');

CREATE POLICY "Admin can insert module_lessons"
  ON module_lessons FOR INSERT WITH CHECK (auth.role() = 'service_role');
CREATE POLICY "Admin can update module_lessons"
  ON module_lessons FOR UPDATE USING (auth.role() = 'service_role');
CREATE POLICY "Admin can delete module_lessons"
  ON module_lessons FOR DELETE USING (auth.role() = 'service_role');

CREATE POLICY "Admin can insert module_topics"
  ON module_topics FOR INSERT WITH CHECK (auth.role() = 'service_role');
CREATE POLICY "Admin can update module_topics"
  ON module_topics FOR UPDATE USING (auth.role() = 'service_role');
CREATE POLICY "Admin can delete module_topics"
  ON module_topics FOR DELETE USING (auth.role() = 'service_role');

CREATE POLICY "Admin can insert module_resources"
  ON module_resources FOR INSERT WITH CHECK (auth.role() = 'service_role');
CREATE POLICY "Admin can update module_resources"
  ON module_resources FOR UPDATE USING (auth.role() = 'service_role');
CREATE POLICY "Admin can delete module_resources"
  ON module_resources FOR DELETE USING (auth.role() = 'service_role');

CREATE POLICY "Admin can insert quiz_questions"
  ON quiz_questions FOR INSERT WITH CHECK (auth.role() = 'service_role');
CREATE POLICY "Admin can update quiz_questions"
  ON quiz_questions FOR UPDATE USING (auth.role() = 'service_role');
CREATE POLICY "Admin can delete quiz_questions"
  ON quiz_questions FOR DELETE USING (auth.role() = 'service_role');
