-- Migration 052: SmartBoard 3.0 — Base Tables
-- Adds: dani_memory, early_warnings, learning_plans, feature_flags
-- All idempotent via DO blocks.

-- ── dani_memory ──────────────────────────────────────────────
-- Persistent memory for Dani AI tutor, replaces localStorage storage.
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'dani_memory') THEN
    CREATE TABLE dani_memory (
      id                    UUID DEFAULT gen_random_uuid() PRIMARY KEY,
      student_id            UUID NOT NULL REFERENCES students(id) ON DELETE CASCADE,
      communication_style   TEXT CHECK (communication_style IN ('shy', 'direct', 'playful', 'curious')),
      strengths             TEXT[] DEFAULT '{}',
      weaknesses            TEXT[] DEFAULT '{}',
      interests             TEXT[] DEFAULT '{}',
      frequent_errors       TEXT[] DEFAULT '{}',
      pending_topics        TEXT[] DEFAULT '{}',
      last_mood             TEXT,
      last_updated          TIMESTAMPTZ DEFAULT NOW(),
      created_at            TIMESTAMPTZ DEFAULT NOW(),
      UNIQUE (student_id)
    );

    ALTER TABLE dani_memory ENABLE ROW LEVEL SECURITY;

    CREATE POLICY "Students read own dani_memory"
      ON dani_memory FOR SELECT
      USING (student_id IN (
        SELECT id FROM students WHERE auth_id = auth.uid()
      ));

    CREATE POLICY "Students write own dani_memory"
      ON dani_memory FOR ALL
      USING (student_id IN (
        SELECT id FROM students WHERE auth_id = auth.uid()
      ));

    CREATE INDEX idx_dani_memory_student ON dani_memory(student_id);
  END IF;
END $$;

-- ── early_warnings ───────────────────────────────────────────
-- Detected academic risk alerts per student.
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'early_warnings') THEN
    CREATE TABLE early_warnings (
      id              UUID DEFAULT gen_random_uuid() PRIMARY KEY,
      student_id      UUID NOT NULL REFERENCES students(id) ON DELETE CASCADE,
      severity        TEXT NOT NULL CHECK (severity IN ('low', 'medium', 'high')),
      type            TEXT NOT NULL,   -- 'inactivity' | 'performance_drop' | 'repeated_errors' | 'low_completion' | 'streak_breaks'
      evidence_json   JSONB DEFAULT '{}',
      recommendation  TEXT,
      resolved_at     TIMESTAMPTZ,
      created_at      TIMESTAMPTZ DEFAULT NOW()
    );

    ALTER TABLE early_warnings ENABLE ROW LEVEL SECURITY;

    CREATE POLICY "Students read own warnings"
      ON early_warnings FOR SELECT
      USING (student_id IN (
        SELECT id FROM students WHERE auth_id = auth.uid()
      ));

    CREATE INDEX idx_early_warnings_student ON early_warnings(student_id, created_at DESC);
    CREATE INDEX idx_early_warnings_unresolved ON early_warnings(student_id) WHERE resolved_at IS NULL;
  END IF;
END $$;

-- ── learning_plans ───────────────────────────────────────────
-- Adaptive learning plans generated by AdaptiveLearningEngine.
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'learning_plans') THEN
    CREATE TABLE learning_plans (
      id              UUID DEFAULT gen_random_uuid() PRIMARY KEY,
      student_id      UUID NOT NULL REFERENCES students(id) ON DELETE CASCADE,
      type            TEXT NOT NULL CHECK (type IN ('daily', 'weekly', 'monthly')),
      plan_json       JSONB NOT NULL DEFAULT '{}',
      generated_at    TIMESTAMPTZ DEFAULT NOW(),
      expires_at      TIMESTAMPTZ,
      is_active       BOOLEAN DEFAULT TRUE
    );

    ALTER TABLE learning_plans ENABLE ROW LEVEL SECURITY;

    CREATE POLICY "Students read own plans"
      ON learning_plans FOR SELECT
      USING (student_id IN (
        SELECT id FROM students WHERE auth_id = auth.uid()
      ));

    CREATE POLICY "Service role writes plans"
      ON learning_plans FOR ALL
      USING (auth.role() = 'service_role');

    CREATE INDEX idx_learning_plans_student_active ON learning_plans(student_id, type) WHERE is_active = TRUE;
  END IF;
END $$;

-- ── feature_flags ────────────────────────────────────────────
-- Per-user feature flag overrides for gradual SmartBoard 3.0 rollout.
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'feature_flags') THEN
    CREATE TABLE feature_flags (
      id          UUID DEFAULT gen_random_uuid() PRIMARY KEY,
      student_id  UUID NOT NULL REFERENCES students(id) ON DELETE CASCADE,
      flags       JSONB NOT NULL DEFAULT '{}',
      updated_at  TIMESTAMPTZ DEFAULT NOW(),
      UNIQUE (student_id)
    );

    ALTER TABLE feature_flags ENABLE ROW LEVEL SECURITY;

    CREATE POLICY "Students read own flags"
      ON feature_flags FOR SELECT
      USING (student_id IN (
        SELECT id FROM students WHERE auth_id = auth.uid()
      ));

    CREATE INDEX idx_feature_flags_student ON feature_flags(student_id);
  END IF;
END $$;
